name: Sync to Personal Fork

on:
  push:
    branches:
      - main   # trigger only when org main is updated

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout org repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to personal fork
        run: |
          git config user.name "moelak"
          git config user.email "moe.lak20@gmail.com"
          git remote add fork https://x-access-token:${{ secrets.PERSONAL_FORK_TOKEN }}@github.com/moelak/fraudog-app.git
          git push fork main --force
